name: publish

on:
  push:
    branches: [ "main", "releases/**" ]
    tags: [ "v*" ]

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        name: setup java
        with:
          java-version: 8
      - name: Publish package
        run: |
          chmod +x ./gradlew
          echo -n "$GPG_PRIVATE_KEY" | base64 --decode > ${GPG_RING_FILE}
          sed -i -e "s,sonatypeUsername=,sonatypeUsername=$SONATYPE_USERNAME,g" gradle.properties
          sed -i -e "s,sonatypePassword=,sonatypePassword=$SONATYPE_PASSWORD,g" gradle.properties
          sed -i -e "s,signing.keyId=,signing.keyId=$GPG_KEY_ID,g" gradle.properties
          sed -i -e "s,signing.password=,signing.password=$GPG_PASSWORD,g" gradle.properties
          sed -i -e "s,signing.secretKeyRingFile=,signing.secretKeyRingFile=$GPG_PRIVATE_KEY,g" gradle.properties
          ./gradlew build publish --warn --stacktrace
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_RING_FILE: ${{ github.workspace }}/key.gpg
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_TOKEN }}