name: publish

on:
  push:
    branches: [ "main", "releases/**" ]
    tags: [ "v*" ]

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Export siging file
        run: echo -n "$GPG_PRIVATE_KEY" | base64 --decode > ${SIGNING_SECRET_KEY_RING_FILE}
        env:
          SIGNING_SECRET_KEY_RING_FILE: ${{ github.workspace }}/key.gpg
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Publish package
        run: gradle publish
        env:
          SIGNING_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ github.workspace }}/key.gpg
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}